### ISSUE TITLE
add PIN support

### ISSUE THREAD

**Issue by moneyball** [photon-sdk/photon-keyserver#2]
1. Add PIN support which requires client to supply a PIN as part of authentication to access data stored on keyserver

2. Should be optional and determined by client

3. PIN digit size could be configurable by client (perhaps 4 digit minimum? 6 digit default? Should there be a max (beyond max integer size)?

**Comment by tanx** [comment]
> 3\. PIN digit size could be configurable by client (perhaps 4 digit minimum? 6 digit default? Should there be a max (beyond max integer size)?

Implemented in #12 ... the pin is optional and can be any length between 4 and 256 characters. That allows for 4 digit pins as well as a passphrase in the library. The rate limit is hit after 10 incorrect tries. Users have to wait 7 days before they can attempt recovery again. This way It would take about 19 years to brute force all combinations in a 4 digit pin.
