### ISSUE TITLE
add time delay

### ISSUE THREAD

**Issue by moneyball** [photon-sdk/photon-keyserver#3]
Add a time delay that helps mitigate SIM jack and cloud account attacks by giving users time to respond.

Similar to Coinbase Vault 48 hour delay:
https://help.coinbase.com/en/coinbase/getting-started/other/vaults-faq.html

or Casa 7 day delay:
https://support.keys.casa/en/docs/201-the-recovery-key-in-keymaster

Allow client to optionally configure a time delay of N (hours, days, etc.) before the server provides the client with data upon successful authentication.

Successful authentication could mean different things:
1) It could be verified SMS _and_ PIN
2) Or just verified SMS (a wallet design might want to require the user to either enter a PIN _or_ wait, say, 7 days)

Send user multiple notifications during the N time window.

As the user could very well not be receiving SMS messages if they've been SIM jacked, consider also adding the ability to store an email which can receive notifications too.

**Comment by tanx** [comment]
> Successful authentication could mean different things:
> 
> 1. It could be verified SMS _and_ PIN
> 2. Or just verified SMS (a wallet design might want to require the user to either enter a PIN _or_ wait, say, 7 days)

Time delayed recovery is now implemented. The workflow is documented in the photon-lib README: https://github.com/photon-sdk/photon-lib/blob/master/README.md#example

> As the user could very well not be receiving SMS messages if they've been SIM jacked, consider also adding the ability to store an email which can receive notifications too.

Email is supported by the key server now too as a fallback option to SMS.
